### ISSUE TITLE
Add Wikipedia scenario

### ISSUE THREAD

**Issue by hvdsomp** [hvdsomp/signposting#10]
Geoff just joined our quest. Welcome! 

He came up with a very interesting scenario that I feel we should add. This is Geoff's description:

---start---

It seems that there is another scenario where this would be useful- that being where the access URI is likely to experience 'content drift', and so you want an identifier URI that represents a stable version suitable for citation. Classic example is a Wiki page, where the content at the access URI is likely to change frequently, and so a specific stable citation URI is provided to point to a particular version.

So if you wanted to cite a particular version of this article:

https://en.wikipedia.org/wiki/Jorge_Luis_Borges

You would click on the so-called permanent link button and get this URL to a stable version of that won't experience the content drift of the main article URI.

https://en.wikipedia.org/w/index.php?title=Jorge_Luis_Borges&oldid=790794828

It seems that use of the identifier link relation would make this much easier.

(BTW- Wikipedia does, of course, get cited in the scholarly literature despite all the guff about not citing it)

---end---

I honestly wasn't aware of this, but in the left column of a wikipedia page, there is a "permanent link" tool and also a "cite this page" tool. In both cases, the returned URL is the "oldid" URL (versioned URL) and not the generic URL. This means that Wikipedia wants the "oldid" URL to be used for referencing. Hence, it qualifies for the "identifier" link. 

There is also a way to follow your nose back from an olidid URL to the generic URL (which was the one in the address bar) by following the "canonical" link. It would be nice if Wikipedia could add Memento's "original" link to that. But that resorts under the long standing a Memento/Wikipedia saga ...

**Comment by jkunze** [comment]
Nice! I didn't know about tthe wikipedia permanent link feature either.

**Comment by hvdsomp** [comment]
Added the scenario as "Version Identifiers". Leaving the issue open for now, in case there would be a need to further discuss.

**Comment by hvdsomp** [comment]
Closing as the scenario is in I-D-00, now, and was OK-ed by all co-authors.
