### ISSUE TITLE
FAIR Signposting Profile: who's the target audience?

### ISSUE THREAD

**Issue by lucboruta** [hvdsomp/signposting#12]
I don't have feedback on the recipe itself, I wholeheartedly agree with the technical recommendations. The FAIR data principles have been quite popular, and I think Signposting is a great example of practices that foster FAIRness.

That said, who's the target audience? Developers who want to ride the FAIR wave, or FAIR aficionados who want to put their metadata where their mouth is?

I think that the connection between Signposting and FAIRness is rather obvious to readers familiar with linked data, but I doubt it is as evident to less-technical readers (who might still be familiar with FAIR, because it's everywhere these days).

The body of the document is fairly technical—I always assume that half of the audience will browse away at the first sight of monospaced fonts—and I'm not sure less-technical readers will understand that:
- Increasing the FAIRness of scholarly objects for machine agents also increases their FAIRness for humans
- Signposting has a ridiculously low cost of entry (if you serve scholarly content over HTTP, you're already almost there)

Specifically:
- "a concrete recipe that repositories can follow": will publishers understand that their websites are included, too, when you mention repositories?
- "widely implemented web protocols specified in IETF RFCs": while this is true, it doesn't really highlight the low cost of entry of Signposting (we're talking about HTTP headers, which any web dev should be able to tweak)

(I might be projecting my own insecurities about persuading non-technical audiences.)

**Comment by hvdsomp** [comment]
Thanks a lot for these comments @lucboruta ! It is very reassuring to hear from you that the tech recommendations are solid!!!

The audience for the document is really techie/implementer. It is an implementation guideline, after all. The intro, however, should be accessible to a broader audience that is familiar with the FAIR quest. Your feedback will definitely help with that regard. In addition, some "promotional material" should be created to accompany this spec so a non-tech audience can understand its value proposition and then go talk to the techies in their org to suggest implementing it. Maybe I can convince my own organization that is very active regarding FAIR to take a stab at that.

**Comment by hvdsomp** [comment]
It seems to me that this issue was noted. At my end, I've involved several colleagues at DANS in Signposting matters and hope they will keep spreading the message in the many projects they are involved in.
