### ISSUE TITLE
Clarity - Can first description and definitions be combined in section 1.1

### ISSUE THREAD

**Issue by zimeon** [hvdsomp/signposting#13]
In [section 1.1. A Scholarly Object on the Web](https://signposting.org/FAIR/#intro1) there is first a list of parts of a scholarly object and then, after the diagram, another list defining most of the terms in the first list. I think it might be clearer to have one set of bullets that does both things.

**Comment by hvdsomp** [comment]
Agreed. I reworked the section along the suggested lines, see [https://signposting.org/FAIR/#intro1](https://signposting.org/FAIR/#intro1).

**Comment by hvdsomp** [comment]
This issue was addressed. Closing,
