### ISSUE TITLE
origin vs. context

### ISSUE THREAD

**Issue by zimeon** [hvdsomp/signposting#14]
With memories of https://github.com/hvdsomp/signposting/issues/1 I was curious about the choice of "origin" as the source or anchor of a link. I think overall that "origin" is much intuitive than "context" but I wonder whether a note to connect origin to the context of [RFC5988](https://tools.ietf.org/html/rfc5988#page-7) would be worthwhile?

**Comment by hvdsomp** [comment]
Agreed. I edited the section in which link `origin` and `target` are introduced, see [https://signposting.org/FAIR/#intro2](https://signposting.org/FAIR/#intro2). Note that the authoritative RFC is meanwhile [RFC8288](https://tools.ietf.org/html/rfc8288) ;-)

**Comment by hvdsomp** [comment]
This issue was addressed. Closing.
