### ISSUE TITLE
Is it FAIR to link metadata?

### ISSUE THREAD

**Issue by zimeon** [hvdsomp/signposting#15]
Reading the FAIR profile I feel the metadata is a little bit left out. It is suggested that metadata is linked to with `describedby` and then typed with `type`, but there is no suggestion of linking from metadata (with, e.g. `describes` per https://signposting.org/bibliographic_metadata/hydra/). I understand the tradeoff between keeping the profile simple (and thus easier to describe and implement) or making it more complete, but I do wonder whether saying something more about the metadata in level 1 would be worthwhile. At level 2 it might also be reasonable to recommend linking to the linkset from both content resource and metadata.

**Comment by hvdsomp** [comment]
Regarding `describes` linking from metadata: The idea was indeed to keep the profile as simple as possible and this type of link (although included in the [Signposting Bibliographic Metadata](https://signposting.org/bibliographic_metadata/)) didn't strike me as convincing when it comes to Return On Investment. In the end, these links are there to help a bot navigate away (in an informed manner) from a resource it somehow lands upon. It felt like the chances were slim that a bot would "out of the blue" land upon a bibliographic metadata resource, when compared to the chances for landing on a landing page (heh), a PDF, etc. 

Regarding the Level 2 remarks:

- The recommendation to link from content resources to link set is already in place, see [https://signposting.org/FAIR/#level2](https://signposting.org/FAIR/#level2)
- Regarding linking from metadata to link set,see the argumentation above

Having said that, if convincing cases exist whereby a bot lands "out of the blue" on a metadata resource, inclusion in the spec could be considered.

**Comment by hvdsomp** [comment]
I would be interested to see if anyone has further thoughts about this issue. The current spec does not include `describes` links pointing from descriptive metadata to the landing page.

**Comment by stain** [comment]
It sounds like an optional extra - if the metadata is well behaved it should already have the links inside, but it might instead be using the persistent identifier if it's "extra good". 

Would it be OK to include `cite-as` from the metadata resource to the persistent identifier? If yes, then this would give you a path down again to the landing page. If not, then this justifies the option of having `describes` back again – similar to `item` vs `collection`.

**Comment by hvdsomp** [comment]
optional extra sounds good to me. and, as you indicated, a "describes" link would allow climbing back up to the landing page where "cite-as" to the PID is available.

I'd rather not go with "cite-as" from metadata to PID because that would break the current pattern that is used for content resources which says those can use "cite-as", "author", "license", "type", "describedby" links if they convey info that is different from what is conveyed at the landing page. Following this logic for a metadata resource, one could use a "cite-as" link to point to a PID of the metadata (not of the object as a whole) if that exists .

**Comment by hvdsomp** [comment]
Looking at the FAIR Signposting spec, it looks like including links from the metadata record ("describes" and possibly others) will require dedicated sections at Level 1 and Level 2 to complement the sections that currently exist for Landing Page and Content Resources. I will look into that.

**Comment by hvdsomp** [comment]
After some introspection and offline discussion, the idea is to have the following links for metadata resources:

- optional "describes" from metadata to landing page
- recommended "linkset" from metadata to Link Set (same as for content resources, i.e. provide if you can meaning if you control the metadata resource)

Changes will be made accordingly in the spec, likely in early 08/21.

**Comment by hvdsomp** [comment]
I finally got around to including the `describes` links into the [FAIR Signposting spec](https://signposting.org/FAIR/) as discussed above. Clearly early 08/2021 was wishful thinking ;-)
