### ISSUE TITLE
Use correct mime type for JSON-LD

### ISSUE THREAD

**Issue by acka47** [hvdsomp/signposting#16]
In the document it reads in section 2.:

> Many other bibliographic formats are in use that have `text/plain`, `application/xml`, `application/json`, or `application/json+ld` as MIME type. 

...but the MIME type for JSON-LD is `application/ld+json`.

**Comment by zimeon** [comment]
In addition to the above we should really switch from saying "MIME type" to "media type". In the IIIF specs we clarified that by saying _"The specific media type (often called a MIME type)..."_ (https://iiif.io/api/presentation/3.0/#format)

**Comment by hvdsomp** [comment]
Addressed in new version.
