### ISSUE TITLE
Address multiple Sitemaps in examples / doc?

### ISSUE THREAD

**Issue by phonedude** [hvdsomp/signposting#18]
Some sites have multiple Sitemaps, like cnn.com*, which although is not a scholarly repository, is typical of how some sites use Sitemaps (i.e., not just a a Sitemap of Sitemaps for hierarchical pagination). 

An example with > 1 Sitemap might remove any ambiguity that might arise during implementation.

* cnn.com Sitemap list:

https://www.cnn.com/robots.txt
Sitemap: https://www.cnn.com/sitemaps/cnn/index.xml
Sitemap: https://www.cnn.com/sitemaps/cnn/news.xml
Sitemap: https://www.cnn.com/sitemap/news.xml
Sitemap: https://www.cnn.com/sitemaps/sitemap-section.xml
Sitemap: https://www.cnn.com/sitemaps/sitemap-interactive.xml
Sitemap: https://www.cnn.com/ampstories/sitemap.xml
Sitemap: https://edition.cnn.com/sitemaps/news.xml
Sitemap: https://www.cnn.com/sitemap/article/cnn-underscored.xml
Sitemap: https://www.cnn.com/sitemap/section/cnn-underscored.xml
Sitemap: https://www.cnn.com/cnn-underscored/money/sitemap.xml
Sitemap: https://www.cnn.com/cnn-underscored/money/sitemap-news.xml
Sitemap: https://www.cnn.com/sitemap/section/politics.xml
Sitemap: https://www.cnn.com/sitemap/article/opinions.xml
Sitemap: https://www.cnn.com/sitemap/article.xml
Sitemap: https://www.cnn.com/sitemap/section.xml
Sitemap: https://www.cnn.com/sitemap/video.xml
Sitemap: https://www.cnn.com/sitemap/gallery.xml

**Comment by hvdsomp** [comment]
With scholcomm repos, one should be happy when there even exists a single sitemap that makes items of a collection discoverable ;-) But, agreed with your observation. I think it generally applies: More than one affordance of the same type can exist. That should be handled by multiple anchor members that use the same service-* links and link targets. Will reflect this on both text and examples.

**Comment by hvdsomp** [comment]
Changed wording regarding the anchor for collection-level affordances to:

Collection-level affordance: The value of the `anchor` member is the URL of the machine interface. If more than one affordance of the same type exist, a distinct `anchor`  member must be used for each.

If I find a repository with multiple sitemaps used to make collection items discoverable, I will add it.

**Comment by phonedude** [comment]
yeah, for repo folk, they might have 0 Sitemaps or 37 ;-)

this is a good solution.
