### ISSUE TITLE
Have a Memento example? 

### ISSUE THREAD

**Issue by phonedude** [hvdsomp/signposting#19]
Showing how to specify TimeGate and TimeMap endpoints would be useful, esp. for repos that support versioning on their holdings.

**Comment by hvdsomp** [comment]
do we know of any scholcomm repos that support Memento? If so I'd be happy to add a Memento example to [https://signposting.org/API-Catalog/#exaffordances](https://signposting.org/API-Catalog/#exaffordances).

**Comment by hvdsomp** [comment]
Added a fictitious Memento example. Will replace with real one if one shows up. There should be some because Fedora 6.x supports Memento.
