### ISSUE TITLE
copy edits

### ISSUE THREAD

**Issue by martinklein0815** [hvdsomp/signposting#22]
The anchor member is the context for links to resources that provide information about the interoperability affordance. These links must have the service-doc, service-desc, and service-meta link relation types with semantics as described in Section 2.2. Links with other link relation types must not be provided.

- Reads as if all anchors MUST have all 3 links, even service-meta? Seems odd, especially when we have a type and profile.
- Example in 3.1 does not show all 3 links per anchor, so I assume its just a wording issue.

**Comment by martinklein0815** [comment]
The repository must support issuing an HTTP HEAD request against its baseURL.
=>
The repository must support issuing an HTTP HEAD request against its baseURL and should, just like for a HTTP GET request, provide a link to the API Catalog Link Set with the api-catalog link relation type.

**Comment by martinklein0815** [comment]
section 3.1
The below example illustrates how an agent can discover a repository's API Catalo.
=>
The below example illustrates how an agent can discover a repository's API Catalog.

The Link Set in the response contains four anchor members, indicating that the repository provides details about four interoperability affordances:
 =>
The Link Set in the response contains five anchor members, indicating that the repository provides details about five interoperability affordances:

(maybe just drop the number, so we don't have to keep fixing it)

No further information is provided for this affordance. Further information about the repository's SPARQL end-point is provided by means of a link with the service-meta link relation type that points at the URL of a SPARQL Description document.
=>
Further information about the repository's SPARQL end-point is provided by means of a link with the service-meta link relation type that points at the URL of a SPARQL Description document.

**Comment by hvdsomp** [comment]
Edits done, new version online and memento of new version at [http://web.archive.org/web/20231121072820/https://signposting.org/API-Catalog/](http://web.archive.org/web/20231121072820/https://signposting.org/API-Catalog/)
