### ISSUE TITLE
Link from landing page to API-Catalog?

### ISSUE THREAD

**Issue by hvdsomp** [hvdsomp/signposting#23]
Sounds good! Then if we have https://example.org/archive1 and  https://example.org/database2, an **api-catalog** link relation type or well-known/api-catalog MUST be available via both baseURLs  
To make it crystal clear where to find the api-catalog, it would also be good to have a '**repository**' link relation type which can be placed at each landing page ('**collection**')
This would allow to consistently use signposting to find my way back to a repository (and from there to further services) even if my journey started at a landing page which I found via a search engine.

_Originally posted by @huberrob in https://github.com/hvdsomp/signposting/issues/21#issuecomment-1820647138_

**Comment by hvdsomp** [comment]
While I am personally not really convinced about the need for a link to support discovery of the API Catalog from an individual object managed by a repository (i.e. link from its landing page), I do not think that a special-purpose link relation type needs to be introduced if one wants such link. The `api-catalog` link type can be used. The question is whether the API Catalog spec needs to advocate for it. Ideas?

**Comment by huberrob** [comment]
For machines it is sometimes not trivial to find the way from a 'collection' aka landing page back to the responsible **repository**. Often this is indicated in enclosed or (signposting) linked metadata e.g. via dc:publisher but also very often not using an URI.

For scientific search engines and catalogs having such a link relation could be a great way to easily extend their indexes using signposting to find more content in case e.g. datasets of a distinct repository are frequently linked via e.g. dc.relation or so.

I agree that **api-catalog** via landing page can also be used to do this and honestly for me this would be the preferred solution. 

Maybe you can mention in the specs that api-catalogs COULD be linked via landing pages? If not I would vote for a **repository** link there..

**Comment by hvdsomp** [comment]
We can’t just make up a **repository** link relation type. I checked the IESG registry and none of the registered link relation types apply. But, again, I don’t see why **api-catalog** wouldn’t do the trick especially since we already advise using it at the baseURL. So, yes, language could be added to advise using it at the landing page level.

**Comment by huberrob** [comment]
OK so the docs simply could mention the possibility to use the api-catalog also at landing-page level? 
This would be good in case landing page baseURLs are differing from repository baseURL so machines would find their way back from landing pages to the repository.

**Comment by hvdsomp** [comment]
Added language re api-catalog link from landing pages:

Moreover, repositories should consider to also provide an `api-catalog` link with the same characteristics, pointing from landing pages of objects managed by the repository to the API Catalog Link Set. This is especially helpful when determining the repository's **baseURL** from landing page URLs is not trivial.
