### ISSUE TITLE
Add examples for advertizes IIIF and Notify protocol

### ISSUE THREAD

**Issue by abollini** [hvdsomp/signposting#25]
It would be nice to include examples about advertising the usage of the IIIF APIs and support for the COAR Notify protocol.

For the IIIF APIs should we focus on the IIIF Presentation API that eventually advice the usage of the other APIs (Image, Search, Auth)?
https://iiif.io/api/presentation/3.0/

For COAR Notify should we advice the usage of the LDN https://www.w3.org/TR/ldn/  providing the repository inbox url as anchor?

**Comment by hvdsomp** [comment]
Will definitely add LDN Inbox to the examples section. 

Regarding IIIF: Presentation API seems good for now. I am OK to add others but would love it if you could send me real life examples.

**Comment by hvdsomp** [comment]
added examples

**Comment by abollini** [comment]
@hvdsomp I'm not convinced by the IIIF example, I will provide you a different reference in a couple of days. I guess that we should use the iiif presentation manifest URL as anchor instead than the "viewer" url but let me found a good example using a DSpace repository to make the point ;)
