### ISSUE TITLE
API Catalog name

### ISSUE THREAD

**Issue by hvdsomp** [hvdsomp/signposting#27]
While the work is based on the api-catalog Internet Draft, I am wondering whether using _API Catalog_ as the term to refer to the document that provides an overview of a repository's interoperability affordances is the best we can do. Especially since it goes quite a bit beyond what is commonly understood as being APIs and includes support for specs like PMH, SPARQL, ... and even things like Signposting, RO-Crate, ...

What to do? Ideas for catchy alternative names?

**Comment by martinklein0815** [comment]
Reading the updated spec just now, I had the same thought. The spectrum of examples provided already goes beyond what is commonly referred to as APIs. The text uses "affordances" but, IMO, "affordance catalog" does not sound great. Maybe: "interoperability services", "FAIR support services (FAIRssCat)" are better options?

**Comment by hvdsomp** [comment]
I was just thinking of InterOPS

**Comment by abollini** [comment]
Is 'standards' catalog too pretentious?
Machine's features?

**Comment by phonedude** [comment]
FAIRcat

(for FAIR Catalog)

rolls of the tongue nicely, incorporates the appropriate acronym (FAIR), captures "catalog"

**Comment by hvdsomp** [comment]
Loving it! Even works when the long name is FAIR Interoperability Catalogue. FAIRcat is great IMO!

**Comment by EnnoMeijers** [comment]
On second thoughts, adding the 'i' to make it FAIRiCat would be a more precise name for a 'FAIR interoperability Catalog' spec and gives the name cheerful twist.

**Comment by huberrob** [comment]
Great! both versions FAIRiCat or FAIRiCAT are perfect

**Comment by hvdsomp** [comment]
Thanks all for input. Changed name to FAIRiCat. Made necessary changes in document. Made publicly available at [https://signposting.org/FAIRiCat/](https://signposting.org/FAIRiCat/). Put redirect in place from API Catalog URL.
