### ISSUE TITLE
Out-of-scope section

### ISSUE THREAD

**Issue by martinklein0815** [hvdsomp/signposting#28]
Basically, do we need one?
The discussion about naming the baby has touched up this. We include a number of interoperability affordances, the spectrum of which is, surely, broad. Would the document benefit from a short list of examples that should not appear in the catalog document, aka are out-of-scope? I am unsure.

**Comment by hvdsomp** [comment]
@martinklein0815 Which kind of things are you thinking of as out of scope? And what kind of harm do you see in listing such things?
