### ISSUE TITLE
Broken Link to Linkset Section

### ISSUE THREAD

**Issue by mugraph** [hvdsomp/signposting#31]
The link to section 1.4 in the paragraph below is missing an `#` to link to the correct anchor.

"For web resources of any media type: Using a standalone document called a Link Set that is made discoverable by means of a typed link with the linkset relation type. More details on Link Set are provided in [Section 1.4](https://signposting.org/FAIR/linksetrec)"

Nice read otherwise :slightly_smiling_face:

**Comment by hvdsomp** [comment]
Thanks for the feedback! Fixed.
