### ISSUE TITLE
Document Holofood signposting

### ISSUE THREAD

**Issue by stain** [hvdsomp/signposting#34]
https://www.holofooddata.org/ is a registry of samples and data collected for Hologenomics for sustainable food production. Signposting is used to provide a link from HTML landing page to its corresponding REST API as JSON, with a [OpenAPI](https://swagger.io/specification/) indicated as its `profile`.

This is an example of _minimal_ signposting, when no FAIR formats are available yet.

```
$ signposting https://www.holofooddata.org/sample/SAMEA10104908
Signposting for https://www.holofooddata.org/sample/SAMEA10104908 
Collection: <https://www.holofooddata.org/api/samples>
DescribedBy: <https://www.holofooddata.org/api/samples/SAMEA10104908> application/json
```

```
$ curl --head https://www.holofooddata.org/sample/SAMEA10104908 | grep Link

Link: <https://www.holofooddata.org/api/samples/SAMEA10104908> ; 
    rel="describedBy" ; type="application/json" ; profile="https://www.holofooddata.org/api/openapi.json", 
Link: <https://www.holofooddata.org/api/samples> ; 
   rel="collection" ; type="application/json" ; profile="https://www.holofooddata.org/api/openapi.json"
```

Contact @SandyRogers for any questions/improvements.

**Comment by hvdsomp** [comment]
They got their `describedby` wrong. They use `describedBy` instead. @stain can you inform them?

**Comment by hvdsomp** [comment]
[@SandyRogers](https://github.com/SandyRogers) Your `Link` header implementation uses `describedBy` instead of `describedby` as a link relation type. The latter one is registered in the [IANA Link Relation Registry](https://www.iana.org/assignments/link-relations/link-relations.xml) and used in FAIR Signposting.

**Comment by hvdsomp** [comment]
Added entry for the Holofood portal at [https://signposting.org/adopters/#holofood](https://signposting.org/adopters/#holofood)

**Comment by SandyRogers** [comment]
@hvdsomp Thanks - fixed by https://github.com/EBI-Metagenomics/holofood-database/commit/28707e24827440b2c50eda0fe3baa17852cf02d8
