### ISSUE TITLE
Link to EOSC Task Force deliverable

### ISSUE THREAD

**Issue by stain** [hvdsomp/signposting#38]
As this report can be hard to find for signposters, suggest adding it to https://signposting.org/#about or https://signposting.org/adopters/

Citation for EOSC Task force deliverable on Signposting adoption:

Mark D Wilkinson, Susanna-Assunta Sansone, Marjan Grootveld, Richard Dennis, David Hecker, Robert Huber, Stian Soiland-Reyes, Herbert Van de Sompel, Andreas Czerniak, Milo Thurston, Allyson L. Lister, Alban Gaignard (2024):
**Report on FAIR Signposting and its Uptake by the Community**.
_EOSC FAIR Metrics and Data Quality Task Force_
<https://doi.org/10.5281/zenodo.10490289>

That was published by [FAIR Metrics and Data Quality](https://eosc.eu/advisory-groups/fair-metrics-and-data-quality)

Note that the new task force is [FAIR Metrics and Digital Objects Task Force](https://eosc.eu/advisory-groups/fair-metrics-and-digital-objects-task-force/)

**Comment by hvdsomp** [comment]
Done on home page [https://signposting.org/](https://signposting.org/)
