### ISSUE TITLE
Wrong media type `application/json+linkset` instead of `application/linkset+json`

### ISSUE THREAD

**Issue by ptamarit** [hvdsomp/signposting#41]
_For FAIR Signposting (I don't have rights to add the `FAIRSignposting` label to the issue)._

In [1.4. Typed Links Provided in Link Sets](https://signposting.org/FAIR/#linksetrec), in the bullet point:

> Two approaches exist to serialize a Link Set: one is JSON-based (media type `application/json+linkset`) and the other uses the same format as the payload of the HTTP `Link` header (media type `application/linkset`).

The media type is `application/json+linkset` while everywhere else in the document the media type is `application/linkset+json`.

**Comment by hvdsomp** [comment]
Thanks a lot @ptamarit for catching this. Great find! I fixed the error.
