### ISSUE TITLE
URIs for authors of the I-D

### ISSUE THREAD

**Issue by hvdsomp** [hvdsomp/signposting#5]
@zimeon provided his ORCID URI to be used for his authorship entry in the I-D. I was wondering whether we should all do this, especially given the nature of this I-D.

**Comment by phonedude** [comment]
I prefer my cs.odu.edu URI bc of its semantics, and for the same reason I'm not a big fan of "seeing" ORCids bc they lack semantics.  But if that's what everyone else wants, I'll do it.

**Comment by hvdsomp** [comment]
Closing this. The author URIs can be changed whenever an author wants them to change.
